name: Nightly release
on: 
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install and Build
      run: |
        npm ci
        npm run build
        if [ -e ./dist/neutralino.js ]; then echo "OK"; else echo "ERR"; exit 1; fi
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: lib_dist
        path: ./dist/
        
  update-nightly-release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v2
      
    - name: Delete nightly tag
      uses: dev-drprasad/delete-tag-and-release@v0.2.0
      with:
        tag_name: nightly
      env:
        GITHUB_TOKEN: ${{ secrets.COMMIT_TOKEN }}
      
    - name: Download build artifacts 
      uses: actions/download-artifact@v2
      with:
        name: lib_dist
        path: ./dist/
        
    - name: Create Release Notes
      run: |
        chmod +x ./scripts/rz.py
        ./scripts/rz.py create nightly --no-changes --top=":warning: **Nightly build**: This nighly-release may contain experimental features and breaking changes."
        
    - name: Update nightly GitHub release
      uses: ncipollo/release-action@v1
      with:
          name: Neutralino.js nightly release
          bodyFile: ./.tmprz/release_notes.md
          artifacts: dist/*.*
          prerelease: true
          allowUpdates: true
          tag: nightly
          
    - name: Publish to NPM Registry
      run: |
        vprefix=nightly-$(date +"%Y%m%d")
        npm version prerelease --preid=$vprefix --commit-hooks=false --git-tag-version=false
        npm run build
        npm publish --access=public --tag nightly
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          
    - name: Clean Release Notes
      run: |
        ./scripts/rz.py cleanup
        
  publish-to-npm:
    needs: update-nightly-release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v2

    - name: Publish to NPM Registry
      run: |
        vprefix=nightly-$(date +"%Y%m%d")
        npm version prerelease --preid=$vprefix --commit-hooks=false --git-tag-version=false
        npm run build
        npm publish --access=public --tag nightly
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
